mandiant/macos-UnifiedLogs

src/decoders/dns.rs
Thank you for making such a great tool :)
I found a log that allows message mapping, so I added the mapping.
- Fixed #5 
- Added log message mapping for `getaddinfo opt 24(0x18)`
- OS: macOS Ventura version 13.3.1(a)
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8, Chip: Apple M1
In this PR, you will be able to output `getaddinfo opt 24(0x18)` log messages as follows.
```
2023-05-25T14:26:01.419Z,Log,Default,com.apple.mdns,1320352,445,65,/usr/sbin/mDNSResponder,00AA92CEB5C83C1782B3C618AB43D536,2671035,dnssd_server,/usr/sbin/mDNSResponder,00AA92CEB5C83C1782B3C618AB43D536,"[R30457] getaddrinfo start -- flags: 0xFFFFFFFFC000D000, ifindex: 0, protocols: 0, hostname: 3/4T+tvoxjZTC4YJDAjvdw==, options: 0x18 {use-failover, prohibit-encrypted-dns}, client pid: 7235 (CFNetworkAgent), delegator …
```
=> add message mapping for getaddinfo opt 24(0x18)

src/decoders/dns.rs
Hello :) 
I found a log that allows message mapping, so I added the mapping.
- Fixed #6 
- Added log message mapping for `dns records any(255)`
- OS: macOS Ventura version 13.3.1(a)
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8, Chip: Apple M1
In this PR, you will be able to output `dns records any(255)` log messages as follows.
```
2023-05-25T13:37:41.229Z,Log,Default,com.apple.mDNSResponder,3607,445,65,/usr/sbin/mDNSResponder,00AA92CEB5C83C1782B3C618AB43D536,0,Default,/usr/sbin/mDNSResponder,00AA92CEB5C83C1782B3C618AB43D536,"[R29583] DNSServiceQueryRecord(11000, 0, 2S+1MK3Jk+97IvLE4BcGzw==, ANY) STOP PID[97042](com.docker.back)","[R%u] DNSServiceQueryRecord(%X, %d, %{sensitive, mask.hash, mdnsresponder:domain_name}.*P, %{public}s) STOP …
```
=> add message mapping for dns records any(255)

src/decoders/dns.rs
Thank you for maintaining tool :)
I found a log that allows message mapping, so I added the mapping.
- Fixed #7
- Added log message mapping for `getaddinfo opt 0(0x0)`
- OS: macOS Ventura version 13.3.1(a)
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8, Chip: Apple M1
In this PR, you will be able to output `getaddinfo opt 0(0x0)` log messages as follows.
```
2023-05-30T11:13:50.048Z,Log,Default,com.apple.mdns,226945,499,65,/usr/sbin/mDNSResponder,00AA92CEB5C83C1782B3C618AB43D536,0,dnssd_server,/usr/sbin/mDNSResponder,00AA92CEB5C83C1782B3C618AB43D536,"[R4803] getaddrinfo start -- flags: 0xFFFFFFFFC808D000, ifindex: 0, protocols: 0, hostname: 9gRtAPDFjP3TqhKR60S6Lw==, options: 0x0 {}, client pid: 7585 (com.apple.Safar)","[R%u] getaddrinfo start -- flags: 0x%X, ifindex: %d, protocols: …
```
=> add message mapping for getaddinfo opt 0(0x0)

examples/unifiedlog_parser/src/main.rs, examples/unifiedlog_parser_json/src/main.rs, src/chunks/firehose/nonactivity.rs, src/chunks/firehose/signpost.rs
Hi,
Thanks for your great work with this library. I'm employing it to parse the file `system_logs.logarchive` of iOS sysdiagnoses and recently noticed that some log messages are missing in the library's output compared to the macOS Console application.
I've determined two causes for this issue, which this pull request intends to fix:
1. The log messages I'm interested in are stored in the `HighVolume` directory, and contrary to previous assumptions, trace3 files in this directory can contain oversize references.
2. The field `FirehoseNonActivity::data_ref_value` has a size of `u16`, while the field `Oversize::data_ref_index` has a size of `u32`. I observed the output of `log raw-dump` and found that the missing messages have oversize references with a value larger than `u16`. When parsing …
=> Use u32 for FirehoseNonActivity::data_ref_value & Oversize tracking for HighVolume directory

examples/unifiedlog_parser_json/src/main.rs
As discussed in issue #16 to address the files that have invalid json, this small change implements jsonl outputting
=> fix: outputs unifiedlog_parser_json as jsonl fixes #16

src/parser.rs, src/unified_log.rs
Responding to the previously created issue #14, here's a first proposition.
We had to test this on our own sysdiags since we do not have yours available, so it'll need more testing on your end, but we noticed an improvement in peak memory usage from ~970mb to ~600mb when parsing the logs.
There's still improvements to be made of course, we introduced an iterator on the surface but it could potentially be iterators all the way down, however the changes required would be substantial.
Here you'll notice that we moved most of the logic from build_log to a new LogIterator structure that itself is used by build_log.
We didn't address the fact that all data is first loaded as a UnifiedLogData, which in our opinion constitutes most of the remainder of the memory usage, since we don't know if that …
=> Introduce an iter_log method to iterate through logs of a same file

rustfmt.toml, src/dsc.rs, src/parser.rs
Hello,
I just added some changes to have better DX.
I don't really know why the test_data was misaligned with actual tests.
=> test / test_data alignements

Cargo.toml, deny.toml, src/lib.rs, src/preamble.rs
Hello @puffyCid 
This is a revival of the too ambitious https://github.com/mandiant/macos-UnifiedLogs/pull/22.
I plan to provide you with a lot of small, easy to review&merge PRs like this one.
So in this first one : `LogPreamble`
- more `nom` combinators usage 
* direct parsing integers (no need to take then parse)
* direct parsing 3 elements (using nom `tuple` combinator)
* direct final struct creation (no `mut` needed)
- added anyhow `dev` dependency for easy error handling
* no panicable code (I tend to avoid `unwrap`s even in test code when I can)
- added a `parse` function the consumes the input.
* its not really used yet, cause the `detect` one is use
* but the detect one makes you re-parse preamble again in other chunks parser, it's a waste.
* so i'll probably slowly migrate to …
=> shorter logpreamble parse implementation by more nom combinators usage

examples/unifiedlog_iterator/Cargo.toml, examples/unifiedlog_iterator/src/main.rs, src/parser.rs
This change brings support for `jsonl` output. 
The output can be saved to a file, or to the standard output.
If the user does not specify the output format as `-f` parameter, it defaults to autodetect it based on the filename.
The user can also specify to `--append` append or not (default). I found the previous default of appending quite confusing.
Please do not hesitate to correct my code, as I'm not very familiar with Rust. 
For sanity check the csv output before and after my change is the same. 
The parameters are therefore now:
```
Usage: unifiedlog_iterator [OPTIONS]
Options:
-l, --live <LIVE>      Run on live system [default: false]
-i, --input <INPUT>    Path to logarchive formatted directory [default: ]
-o, --output <OUTPUT>  Path to output file. Any directories must already …
```
=> chg: [unifiedlog_iterator] support jsonl output and more params

src/decoders/dns.rs
The primary goal of this PR is to fix an infinite loop that was seen in the wild when parsing DNS entries from a sample with private data logging enabled. This is due to a lack of verification of the IP type (4 vs 6) with no corresponding `else` block in the subsequent parsing loop. I also took the opportunity to do some minor cleanup, reducing some of the parsing down to one-liners with nom.
=> Fix infinite loop in DNS parsing

src/catalog.rs, src/chunks/firehose/activity.rs, src/chunks/firehose/firehose_log.rs, src/chunks/firehose/flags.rs, src/chunks/firehose/loss.rs, src/chunks/firehose/message.rs, src/chunks/firehose/nonactivity.rs, src/chunks/firehose/signpost.rs, src/chunks/firehose/trace.rs, src/chunks/oversize.rs, src/chunks/simpledump.rs, src/chunks/statedump.rs, src/chunkset.rs, src/decoders/location.rs, src/dsc.rs, src/header.rs, src/iterator.rs, src/timesync.rs, src/unified_log.rs, src/uuidtext.rs
Lots of structs are being initialized with default values; therefore,
it makes sense to add the 'Default' derived traits to those structs and
replace default initializations with calls to `default()`.
=> cleanup: Adds 'Default' trait to many structs

src/decoders/dns.rs
This small PR change the `parse_svcb_ip` function impl.
It's a little more complicated (sorry for that), but reduce the number of allocations :
n4 : number of ipv4 addresses
n6 : number of ipv6 addresses
Before : `2 + n4 + n6 + 2 + 1` (2 vecs + to_string for IPs + 2 joins + format!)
After (best case) : `2 + 1` (2 string buffers + format! in the end)
In the worst case, if there are many many ip addresses, String growth will reallocate the buffers, so it might be not that interesting.
What is the expected/usual number of ip addresses here ?
=> less allocations in parse_svcb_ip

src/chunks/firehose/firehose_log.rs
This PR does some refactoring in `firehose_log.rs` that should provide some performance gains by eliminating allocation of several `Vec`s throughout the file. It also simplifies some `nom` parsing, where data was first being extracted with `take` before being handed off to the integer parsers.
=> Firehose Log: Performance + Refactor

.github/workflows/pullrequest.yml, .gitignore, BUILDING.md, tests/big_sur_tests.rs, tests/high_sierra_tests.rs, tests/monterey_tests.rs
PR adds the test `*.rs` files from the tests.zip file in the releases page to the repo.
Updates CI to pull down only the `test_data` now
Should make it easier to make larger changes that may impact test files such as #48 and #34
=> Add test files

src/decoders/darwin.rs, src/decoders/decoder.rs, src/decoders/dns.rs, src/decoders/location.rs, src/decoders/time.rs, src/decoders/uuid.rs
Happy new year here !
This is my last baby step on oxisiding the `decoders` module.
=> some more decoders can now expose the underlying errors

Cargo.toml, src/catalog.rs, src/chunks/firehose/firehose_log.rs, src/iterator.rs, src/unified_log.rs, src/util.rs
It's mainly a big refacto / better nom usage in `catalog.rs`
- code is now shorter
- avoid structs mutation (no need Default anymore in most cases)
`util.rs`
- some more padding functions
- `test_case` usage have more test cases in a short specification
=> catalog.rs improvements

.github/scripts/package.sh, .github/workflows/release.yml, Cargo.toml, deny.toml, src/parser.rs
Small PR before publishing to crates
=> Dependency updates and minor changes

examples/unifiedlog_iterator/src/main.rs, src/iterator.rs, src/parser.rs, src/unified_log.rs, tests/big_sur_tests.rs, tests/high_sierra_tests.rs, tests/monterey_tests.rs
Hi
I think it would make a better interface if we used enums to represent the event type and log type. It also should be more efficient since we are using a pair of enum instead of a string.
We can also more accurately represent the possible states by nesting the log type in the enum variant where it is applicable.
This does make some assumptions about the combination of event type and log type but I think it is correct.
Any feedback is appreciated
=> Change event type and log type to structured enum

.changes/unreleased/Added-20250225-004526.yaml, Cargo.toml, README.md, src/unified_log.rs, tests/big_sur_tests.rs, tests/high_sierra_tests.rs, tests/monterey_tests.rs
This PR adds support for parsing Protobuf data in StateDump log entries. It uses the small [sunlight](https://github.com/puffyCid/sunlight) library to parse the data
=> StateDump Protobuf parsing support

benches/big_sur_benchmark.rs, benches/high_sierra_benchmark.rs, benches/monterey_benchmark.rs, examples/unifiedlog_iterator/src/main.rs, src/catalog.rs, src/chunks/statedump.rs, src/decoders/config.rs, src/decoders/dns.rs, src/decoders/location.rs, src/decoders/uuid.rs, src/dsc.rs, src/header.rs, src/lib.rs, src/message.rs, src/timesync.rs, tests/big_sur_tests.rs, tests/high_sierra_tests.rs, tests/monterey_tests.rs
As of Rust 1.88, there are many clippy warnings throughout the project. I've cleaned them up. Note that there is also a clippy lint that has been removed as of 1.88, which I have removed.
=> Fix clippy warnings
